"""add_overtime_multiplier_to_pay_rates

Revision ID: 67395b656de2
Revises: 564627d65c6d
Create Date: 2026-03-28 02:08:04.862784+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67395b656de2'
down_revision: Union[str, None] = '564627d65c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_pay_rates', sa.Column('overtime_multiplier', sa.Numeric(precision=6, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_pay_rates', 'overtime_multiplier')
    # ### end Alembic commands ###
