"""production_complete

Revision ID: 97e36c30db14
Revises: 002
Create Date: 2026-03-27 01:20:46.591949+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e36c30db14'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'tenant_id',
               existing_type=sa.UUID(),
               comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('invoices', 'po_id',
               existing_type=sa.UUID(),
               comment='FK to contracts.id',
               existing_nullable=True)
    op.alter_column('payroll_runs', 'tenant_id',
               existing_type=sa.UUID(),
               comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('projects', 'tenant_id',
               existing_type=sa.UUID(),
               comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('projects', 'client_id',
               existing_type=sa.UUID(),
               comment='FK to clients.id',
               existing_nullable=True)
    op.alter_column('projects', 'po_id',
               existing_type=sa.UUID(),
               comment='FK to contracts.id',
               existing_nullable=True)
    op.alter_column('timesheets', 'tenant_id',
               existing_type=sa.UUID(),
               comment='FK to tenants.id',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timesheets', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('projects', 'po_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to contracts.id',
               existing_nullable=True)
    op.alter_column('projects', 'client_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to clients.id',
               existing_nullable=True)
    op.alter_column('projects', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('payroll_runs', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('invoices', 'po_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to contracts.id',
               existing_nullable=True)
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tenants.id',
               existing_nullable=False)
    op.alter_column('employees', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to tenants.id',
               existing_nullable=False)
    # ### end Alembic commands ###
